### ISSUE TITLE
Remove volume on stack drop

### ISSUE THREAD

**Issue by BurkhalterY** [remyz17/odooghost#31]
What about removing the volume too when we do `odooghost stack drop`? Because volumes can be very big, depending on which database is restored.

Currently, we have to do:
```bash
odooghost stack drop my-stack
docker volume rm odooghost_my-stack_db_data
docker volume odooghost_my-stack_odoo_data
```

**Comment by BonnetAdam** [comment]
Already exist... Add `--volumes` to `odooghost stack drop`

**Comment by BurkhalterY** [comment]
I'm a big J!!!

**Comment by BurkhalterY** [comment]
Thanks!
